In [9]:
import requests
import tensorflow as tf
from keras.models import load_model
import numpy as np



In [40]:

# Укажите путь к файлу изображения
image_path = "C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/moon-jellyfish.jpg"

# Создайте объект UploadFile, чтобы отправить файл как часть мультипартового запроса
files = {'image_file': open(image_path, 'rb')}

# Отправьте запрос POST на сервер FastAPI
response = requests.post("http://127.0.0.1:8000/model/predict", files=files)

# Проверка кода ответа
if response.status_code == 200:
    print('Изображение успешно отправлено и обработано')
    print('Ответ от сервера:', response.json())
else:
    print('Ошибка при отправке изображения:', response.status_code)


Изображение успешно отправлено и обработано
Ответ от сервера: Moon_jellyfish


In [51]:
image_path = "C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/moon-jellyfish.jpg"
model = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/model_new.h5')
image_pred = Image.open(image_path)
image_pred_resized = image_pred.resize((224, 224))

image_tensor = tf.keras.preprocessing.image.img_to_array(image_pred_resized)
image_tensor = image_tensor[np.newaxis, ...]

In [52]:
model.predict(image_tensor)


1/1 [==============================] - 0s 98ms/step


array([[1., 0., 0., 0., 0., 0.]], dtype=float32)

In [34]:
from scipy.special import softmax

result = model.predict(np.expand_dims(image_tensor, axis=0))
predicted_probabilities = softmax(result, axis=1)
predicted_probabilities

1/1 [==============================] - 0s 94ms/step


array([[0.12956251, 0.12956251, 0.12956251, 0.12956251, 0.35218745,
        0.12956251]], dtype=float32)

In [53]:
# Загрузка модели
model1 = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/model_1.h5')
model2 = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/model_2.h5')
model3 = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/model3_.h5')
model4 = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/model_new.h5')


In [54]:
result = model4.predict(image_tensor)
predicted_probabilities = softmax(result, axis=1)
predicted_probabilities

1/1 [==============================] - 0s 111ms/step


array([[0.35218745, 0.12956251, 0.12956251, 0.12956251, 0.12956251,
        0.12956251]], dtype=float32)

In [55]:
#result = model2.predict(np.expand_dims(image_tensor, axis=0))
result = model2.predict(image_tensor)
predicted_probabilities = softmax(result, axis=1)
predicted_probabilities

1/1 [==============================] - 0s 281ms/step


array([[0.17366765, 0.14662883, 0.14625496, 0.14551769, 0.14049868,
        0.24743223]], dtype=float32)

In [56]:
result = model3.predict(image_tensor)
predicted_probabilities = softmax(result, axis=1)
predicted_probabilities

1/1 [==============================] - 0s 128ms/step


array([[0.35218745, 0.12956251, 0.12956251, 0.12956251, 0.12956251,
        0.12956251]], dtype=float32)

In [57]:
result = model4.predict(np.expand_dims(image_tensor, axis=0))
predicted_probabilities = softmax(result, axis=1)
predicted_probabilities

1/1 [==============================] - 0s 136ms/step


array([[0.35218745, 0.12956251, 0.12956251, 0.12956251, 0.12956251,
        0.12956251]], dtype=float32)