In [13]:
import requests
import tensorflow as tf
from keras.models import load_model
import numpy as np
from PIL import Image



In [40]:

# Укажите путь к файлу изображения
image_path = "C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/moon-jellyfish.jpg"

# Создайте объект UploadFile, чтобы отправить файл как часть мультипартового запроса
files = {'image_file': open(image_path, 'rb')}

# Отправьте запрос POST на сервер FastAPI
response = requests.post("http://127.0.0.1:8000/model/predict", files=files)

# Проверка кода ответа
if response.status_code == 200:
    print('Изображение успешно отправлено и обработано')
    print('Ответ от сервера:', response.json())
else:
    print('Ошибка при отправке изображения:', response.status_code)


Изображение успешно отправлено и обработано
Ответ от сервера: Moon_jellyfish


In [50]:

# Укажите путь к файлу изображения
image_path = "C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/moon-jellyfish.jpg"

# Создайте объект UploadFile, чтобы отправить файл как часть мультипартового запроса
files = {'image_file': open(image_path, 'rb')}

# Отправьте запрос POST на сервер FastAPI
response = requests.post("http://127.0.0.1:8000/classify_image/", files=files)

# Проверка кода ответа
if response.status_code == 200:
    print('Изображение успешно отправлено и обработано')
    print('Ответ от сервера:', response.json())
else:
    print('Ошибка при отправке изображения:', response.status_code)


Изображение успешно отправлено и обработано
Ответ от сервера: jellyfish


In [36]:
image_path = "C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/16.jpg"
model = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/model_new.h5')
image_pred = Image.open(image_path)
image_pred_resized = image_pred.resize((224, 224))

image_tensor = tf.keras.preprocessing.image.img_to_array(image_pred_resized)
image_tensor = image_tensor[np.newaxis, ...]

In [52]:
model.predict(image_tensor)


1/1 [==============================] - 0s 98ms/step


array([[1., 0., 0., 0., 0., 0.]], dtype=float32)

In [34]:
from scipy.special import softmax

result = model.predict(np.expand_dims(image_tensor, axis=0))
predicted_probabilities = softmax(result, axis=1)
predicted_probabilities

1/1 [==============================] - 0s 94ms/step


array([[0.12956251, 0.12956251, 0.12956251, 0.12956251, 0.35218745,
        0.12956251]], dtype=float32)

In [53]:
# Загрузка модели
model1 = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/model_1.h5')
model2 = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/model_2.h5')
model3 = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/model3_.h5')
model4 = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/model_new.h5')


In [54]:
result = model4.predict(image_tensor)
predicted_probabilities = softmax(result, axis=1)
predicted_probabilities

1/1 [==============================] - 0s 111ms/step


array([[0.35218745, 0.12956251, 0.12956251, 0.12956251, 0.12956251,
        0.12956251]], dtype=float32)

In [55]:
#result = model2.predict(np.expand_dims(image_tensor, axis=0))
result = model2.predict(image_tensor)
predicted_probabilities = softmax(result, axis=1)
predicted_probabilities

1/1 [==============================] - 0s 281ms/step


array([[0.17366765, 0.14662883, 0.14625496, 0.14551769, 0.14049868,
        0.24743223]], dtype=float32)

In [56]:
result = model3.predict(image_tensor)
predicted_probabilities = softmax(result, axis=1)
predicted_probabilities

1/1 [==============================] - 0s 128ms/step


array([[0.35218745, 0.12956251, 0.12956251, 0.12956251, 0.12956251,
        0.12956251]], dtype=float32)

In [57]:
result = model4.predict(np.expand_dims(image_tensor, axis=0))
predicted_probabilities = softmax(result, axis=1)
predicted_probabilities

1/1 [==============================] - 0s 136ms/step


array([[0.35218745, 0.12956251, 0.12956251, 0.12956251, 0.12956251,
        0.12956251]], dtype=float32)

In [2]:
# import tensorflow as tf
# from tensorflow.keras.applications import ResNet50
# 
# # Load ResNet50 model
# resnet_model = ResNet50(weights='imagenet')
# 
# # Save the model
# tf.keras.models.save_model(
#     resnet_model,
#     'resnet50_model.h5',  # Specify the path where you want to save the model
#     include_optimizer=False  # Set to False if you don't want to save the optimizer state
# )

A local file was found, but it seems to be incomplete or outdated because the auto file hash does not match the original value of 2cb95161c43110f7111970584f804107 so we will re-download the data.
102967424/102967424 [==============================] - 16s 0us/step


In [15]:
model50 = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/resnet50_model.h5')
result = model50.predict(image_tensor)
result

1/1 [==============================] - 1s 1s/step


array([[8.54536386e-10, 4.98325517e-06, 2.23817787e-09, 2.88158875e-09,
        3.85980886e-10, 3.01607428e-09, 3.88267640e-10, 5.25313126e-10,
        9.63589885e-12, 2.14778993e-11, 1.39854820e-11, 1.08651944e-12,
        1.10859555e-09, 9.96629862e-13, 4.79647572e-11, 1.01522358e-11,
        4.95462308e-12, 2.31529444e-12, 4.54318441e-12, 8.44083831e-12,
        2.15098230e-12, 7.67582775e-13, 3.82096828e-12, 2.04770072e-11,
        7.82462636e-12, 7.37392647e-11, 2.49888638e-10, 1.11980730e-10,
        2.30815381e-10, 1.69292858e-10, 3.68882758e-10, 1.12286725e-11,
        1.03597644e-10, 5.71050263e-10, 1.03382747e-09, 1.20492172e-09,
        6.32711383e-10, 1.83311161e-11, 4.22127047e-12, 6.10875586e-12,
        2.80147975e-12, 1.03610382e-12, 1.50844268e-12, 5.86610057e-12,
        1.07804824e-11, 9.48147897e-12, 9.10493144e-13, 1.60250090e-12,
        4.02957832e-12, 1.10371345e-09, 7.59391161e-10, 8.11118048e-11,
        2.75045348e-10, 8.95119479e-10, 6.35862543e-11, 2.453840

In [30]:
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.resnet import preprocess_input
from tensorflow.keras.applications.resnet50 import decode_predictions

import numpy as np
from PIL import Image

# Load the ResNet50 model from the file
model50 = load_model('C:/Users/Peter/DataspellProjects/kaggle/jellyfish_image_classification/resnet50_model.h5')

# Assuming image_tensor contains the preprocessed image data
# Note: Make sure the image_tensor has the correct shape and preprocessing
# Preprocess the input image data
image_tensor_preprocessed = preprocess_input(image_tensor)

# Compile the model manually
model50.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Predict using the compiled model
result = model50.predict(image_tensor_preprocessed)
result_label = decode_predictions(result, top=1)[0][0][1]

result_label


1/1 [==============================] - 1s 1s/step


'plunger'